"""PDF report generator using fpdf2.

Builds a downloadable report containing:
- Configuration summary
- Top ranked skills table
- Gap analysis results (if available)
- Generated resume bullets (if available)
- Project recommendations
"""

import io
from fpdf import FPDF
from typing import Dict, List, Optional


class RoadmapPDF(FPDF):
    """Custom PDF with header and footer."""

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 10, "Engineering Career Roadmap Report", ln=True, align="C")
        self.set_font("Helvetica", "I", 9)
        self.cell(0, 5, "Generated by Career Roadmap Tool - March 2026", ln=True, align="C")
        self.ln(5)
        # Divider line
        self.set_draw_color(27, 115, 232)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", align="C")


def generate_pdf(
    user_config: Dict,
    ranked_skills: List[Dict],
    gap_results: Optional[Dict] = None,
    bullets: Optional[List[str]] = None,
) -> bytes:
    """Build a PDF report and return it as bytes for st.download_button."""
    pdf = RoadmapPDF()
    pdf.alias_nb_pages()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # ── Section 1: Configuration ──────────────────────────────────────
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Your Profile", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 6, f"Background: {user_config.get('background', 'N/A')}", ln=True)
    industries = ", ".join(user_config.get("industries", []))
    pdf.cell(0, 6, f"Target Industries: {industries}", ln=True)
    pdf.ln(5)

    # ── Section 2: Top Ranked Skills ──────────────────────────────────
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Top Ranked Skills", ln=True)
    pdf.set_font("Helvetica", "", 9)

    # Table header
    pdf.set_fill_color(27, 115, 232)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(15, 7, "Rank", border=1, fill=True, align="C")
    pdf.cell(65, 7, "Skill", border=1, fill=True)
    pdf.cell(40, 7, "Category", border=1, fill=True)
    pdf.cell(25, 7, "Mentions", border=1, fill=True, align="C")
    pdf.cell(30, 7, "Score (%)", border=1, fill=True, align="C")
    pdf.ln()

    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Helvetica", "", 9)
    for i, skill in enumerate(ranked_skills[:25]):
        fill = i % 2 == 0
        if fill:
            pdf.set_fill_color(240, 242, 246)
        pdf.cell(15, 6, str(skill.get("rank", i + 1)), border=1, fill=fill, align="C")
        pdf.cell(65, 6, str(skill.get("canonical", "")), border=1, fill=fill)
        pdf.cell(40, 6, str(skill.get("category", "")), border=1, fill=fill)
        pdf.cell(25, 6, str(skill.get("mention_count", "")), border=1, fill=fill, align="C")
        pdf.cell(30, 6, str(skill.get("priority_score", "")), border=1, fill=fill, align="C")
        pdf.ln()

    pdf.ln(5)

    # ── Section 3: Gap Analysis ───────────────────────────────────────
    if gap_results:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "Skills Gap Analysis", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, f"Coverage Score: {gap_results.get('score', 0)}%", ln=True)
        pdf.ln(3)

        present = gap_results.get("present", [])
        missing = gap_results.get("missing", [])

        if present:
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, "Skills You Have:", ln=True)
            pdf.set_font("Helvetica", "", 9)
            for s in present:
                pdf.cell(0, 5, f"  - {s['canonical']} ({s['priority_score']}%)", ln=True)
            pdf.ln(3)

        if missing:
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, "Skills to Develop:", ln=True)
            pdf.set_font("Helvetica", "", 9)
            for s in missing:
                pdf.cell(0, 5, f"  - {s['canonical']} ({s['priority_score']}%)", ln=True)
            pdf.ln(3)

    # ── Section 4: Resume Bullets ─────────────────────────────────────
    if bullets:
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "ATS-Optimized Resume Bullets", ln=True)
        pdf.set_font("Helvetica", "", 9)
        for bullet in bullets:
            # Use multi_cell for wrapping
            pdf.multi_cell(0, 5, f"* {bullet}")
            pdf.ln(1)

    # ── Section 5: Disclaimer ─────────────────────────────────────────
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(
        0, 4,
        "Disclaimer: Data updated March 2026. Rankings are based on keyword "
        "frequency analysis of job postings and should be used as a guide, "
        "not as a guarantee of hiring outcomes. Always tailor your resume "
        "to each specific job description."
    )

    # Output to bytes
    buffer = io.BytesIO()
    pdf.output(buffer)
    return buffer.getvalue()
